# Default values for
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deployto.io/servicea
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  # className: nginx
  className: servicea-nginx
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: servicea.deploy.to
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com
  # Mostly for argocd or any other CI that uses `helm template | kubectl apply` or similar
  # If helm doesn't correctly detect your ingress API version you can set it here.
  # apiVersion: networking.k8s.io/v1



ingress-nginx:
  enabled: true
  controller:
    ingressClass: servicea-nginx
    ingressClassResource:
      # -- Name of the ingressClass
      name: servicea-nginx
      # -- Is this ingressClass enabled or not
      enabled: true
      # -- Is this the default ingressClass for the cluster
      default: false

postgresql:
  enabled: true
  auth:
    database: "servicea"
    username: "servicea"
    password: "HOrFk14CyX"
    postgresPassword: "xxdsdsddsxxxx"


  