apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config.yaml").AsSecrets | indent 2 }}